[project]
name = "zigchad"
version = "0.1.3"
description = "Download your Zig versions."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.rye]
dev-dependencies = [
    "ruff>=0.13.3",
]

[dependency-groups]
dev = [
    "ruff>=0.13.3",
]
